# Generated by Django 4.1.4 on 2023-01-07 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="gallerypage", name="content",),
        migrations.AddField(
            model_name="gallerypage",
            name="banner_subtitle",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="banner_title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="gallery_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
