# Generated by Django 4.1.4 on 2023-01-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_alter_gallerypage_banner_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerypage",
            name="album_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="description",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
