# Generated by Django 4.1.4 on 2023-01-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_banner_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_subtitle",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
