# Generated by Django 4.1.4 on 2023-01-03 23:17

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_homepage_about_description_homepage_about_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="about_description",
            field=wagtail.fields.RichTextField(max_length=500, null=True),
        ),
    ]
