# Generated by Django 4.1.4 on 2023-01-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_about_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="about_description",
            field=models.TextField(max_length=500, null=True),
        ),
    ]
