# Generated by Django 4.1.4 on 2023-01-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_homepage_about_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="first_service_desciption",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="first_service_title",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="fourth_service_desciption",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="fourth_service_title",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="second_service_desciption",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="second_service_title",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="third_service_desciption",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="third_service_title",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
