# Generated by Django 4.1.4 on 2023-01-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("home", "0008_homepage_first_service_desciption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="gallery_cta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
    ]
