# Generated by Django 4.1.4 on 2023-01-09 09:52

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_homepage_change_icons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="change_icons",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
