# Generated by Django 4.1.4 on 2023-01-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("home", "0015_alter_homepage_change_icons"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("formatted_address", models.CharField(max_length=255)),
                ("latlng_address", models.CharField(max_length=255)),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
    ]
