# Generated by Django 4.1.4 on 2023-01-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_homepage_cards"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage", old_name="cards", new_name="attractions_photos",
        ),
    ]
