# Generated by Django 4.1.4 on 2023-01-11 07:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_remove_homepage_banner_title_and_subtitle_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="title_and_subtitle",),
        migrations.AddField(
            model_name="homepage",
            name="banner_title_and_subtitle",
            field=wagtail.fields.StreamField(
                [
                    (
                        "banner_title_and_subtitle",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add title", required=True
                                    ),
                                ),
                                (
                                    "subtitle",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add subtitle", required=True
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
