# Generated by Django 4.1.4 on 2023-01-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0039_alter_homepage_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage", old_name="icon1", new_name="icon",
        ),
        migrations.RemoveField(model_name="homepage", name="icon2",),
        migrations.RemoveField(model_name="homepage", name="icon3",),
        migrations.RemoveField(model_name="homepage", name="icon4",),
    ]
