# Generated by Django 4.1.4 on 2023-01-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0040_rename_icon1_homepage_icon_remove_homepage_icon2_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="icon",),
    ]
