# Generated by Django 4.1.4 on 2023-01-13 06:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0046_alter_homepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        max_length=255, required=True
                                    ),
                                ),
                                (
                                    "subtitle",
                                    wagtail.blocks.CharBlock(
                                        max_length=255, required=True
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "image_position",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("left-top", "Left Top"),
                                            ("left-center", "Left Center"),
                                            ("left-bottom", "Left Bottom"),
                                            ("center-top", "Center Top"),
                                            ("center-center", "Center Center"),
                                            ("center-bottom", "Center Bottom"),
                                            ("right-top", "Right Top"),
                                            ("right-center", "Right Center"),
                                            ("right-bottom", "Right Bottom"),
                                        ]
                                    ),
                                ),
                                (
                                    "image_size",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("auto", "Auto"),
                                            ("cover", "Cover"),
                                            ("contain", "Contain"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "card",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        required=True
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=40, required=True
                                                    ),
                                                ),
                                                (
                                                    "text",
                                                    wagtail.blocks.TextBlock(
                                                        max_length=200, required=True
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "carousel",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add title", required=True
                                    ),
                                ),
                                (
                                    "subtitle",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add subtitle", required=True
                                    ),
                                ),
                                (
                                    "images",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        required=True
                                                    ),
                                                ),
                                                (
                                                    "caption",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=255, required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                                (
                                    "autoplay",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Autoplay the carousel on page load.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "interval",
                                    wagtail.blocks.IntegerBlock(
                                        default=3000,
                                        help_text="Interval between slides in milliseconds.",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
