# Generated by Django 4.1.4 on 2023-01-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attractionpage",
            name="subtitle_of_attraction",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
