# Generated by Django 4.1.4 on 2023-01-05 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("attractions", "0002_attractionpage_subtitle_of_attraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="attractionpage",
            name="image_of_attraction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
