# Generated by Django 4.1.4 on 2023-01-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0003_attractionpage_image_of_attraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="attractionpage",
            name="description_of_attraction",
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
