# Generated by Django 4.1.4 on 2023-01-05 08:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0005_attractionpage_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attractionpage", name="description_of_attraction",
        ),
        migrations.RemoveField(
            model_name="attractionpage", name="image_of_attraction",
        ),
        migrations.RemoveField(
            model_name="attractionpage", name="subtitle_of_attraction",
        ),
        migrations.RemoveField(
            model_name="attractionpage", name="title_of_attraction",
        ),
        migrations.AlterField(
            model_name="attractionpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_and_text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add title", required=True
                                    ),
                                ),
                                (
                                    "subtitle",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add subtitle", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Add additional text", required=True
                                    ),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ],
                            classname="text_and_title",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
