# Generated by Django 4.1.4 on 2023-01-06 03:12

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0007_alter_attractionpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attractionpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_and_subtitle",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add title", required=True
                                    ),
                                ),
                                (
                                    "subtitle",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add subtitle", required=True
                                    ),
                                ),
                            ],
                            classname="title_and_subtitle",
                        ),
                    ),
                    ("full_richtext", streams.blocks.RichtextBlock()),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
