# Generated by Django 4.1.4 on 2023-01-10 19:27

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0010_delete_gallerypage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attractionpage",
            old_name="content",
            new_name="title_and_subtitle",
        ),
        migrations.AddField(
            model_name="attractionpage",
            name="carousel",
            field=wagtail.fields.StreamField(
                [
                    (
                        "carousel",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "carousel",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        required=True
                                                    ),
                                                ),
                                                (
                                                    "title_of_image",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=40, required=False
                                                    ),
                                                ),
                                                (
                                                    "description_of_image",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=50, required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ],
                            classname="carousel",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
