# Generated by Django 4.1.4 on 2023-01-10 19:32

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        (
            "attractions",
            "0011_rename_content_attractionpage_title_and_subtitle_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="attractionpage", name="carousel",),
        migrations.RemoveField(model_name="attractionpage", name="title_and_subtitle",),
        migrations.AddField(
            model_name="attractionpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_and_subtitle",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add title", required=True
                                    ),
                                ),
                                (
                                    "subtitle",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add subtitle", required=True
                                    ),
                                ),
                            ],
                            classname="title_and_subtitle",
                        ),
                    ),
                    ("full_richtext", streams.blocks.RichtextBlock()),
                    (
                        "carousel",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "carousel",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=True
                                                ),
                                            ),
                                            (
                                                "title_of_image",
                                                wagtail.blocks.CharBlock(
                                                    max_length=40, required=False
                                                ),
                                            ),
                                            (
                                                "description_of_image",
                                                wagtail.blocks.CharBlock(
                                                    max_length=50, required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ],
                            classname="carousel",
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
