# Generated by Django 4.1.4 on 2023-01-15 11:02

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0020_alter_attractionpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attractionpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_and_subtitle",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "subtitle",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="Add subtitle", required=True
                                    ),
                                ),
                                (
                                    "title_class_name",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("fw-light", "FW-LIGHT"),
                                            ("text-muted", "TEXT-MUTED"),
                                        ]
                                    ),
                                ),
                                (
                                    "heading_level",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("h1", "H1"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                            ("h5", "H5"),
                                            ("h6", "H6"),
                                        ]
                                    ),
                                ),
                            ],
                            classname="title_and_subtitle",
                        ),
                    ),
                    ("full_richtext", streams.blocks.RichtextBlock()),
                    (
                        "cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "card",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        required=True
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=40, required=True
                                                    ),
                                                ),
                                                (
                                                    "text",
                                                    wagtail.blocks.TextBlock(
                                                        max_length=200, required=True
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "banner",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        max_length=255, required=True
                                    ),
                                ),
                                (
                                    "subtitle",
                                    wagtail.blocks.CharBlock(
                                        max_length=255, required=True
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "image_size",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("auto", "Auto"),
                                            ("cover", "Cover"),
                                            ("contain", "Contain"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "carousel",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add title", required=True
                                    ),
                                ),
                                (
                                    "subtitle",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add subtitle", required=True
                                    ),
                                ),
                                (
                                    "images",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        required=True
                                                    ),
                                                ),
                                                (
                                                    "caption",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=255, required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                                (
                                    "autoplay",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Autoplay the carousel on page load.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "interval",
                                    wagtail.blocks.IntegerBlock(
                                        default=3000,
                                        help_text="Interval between slides in milliseconds.",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
